# Write Dashboard.tsx using hex encoding to avoid tag stripping
import sys

# The </div> closing tag bytes
CLOSE_DIV = bytes([0x3C, 0x2F, 0x64, 0x69, 0x76, 0x3E])

def build_content():
    lines = []
    lines.append(b'import { useEffect, useState } from "react";')
    lines.append(b'import { useNavigate } from "react-router-dom";')
    lines.append(b'')
    lines.append(b'export default function Dashboard() {')
    lines.append(b'  const navigate = useNavigate();')
    lines.append(b'  const [healthData, setHealthData] = useState<{ status: string; version: string; uptime: number } | null>(null);')
    lines.append(b'  const [conversationCount, setConversationCount] = useState(0);')
    lines.append(b'  const [memoryCount, setMemoryCount] = useState(0);')
    lines.append(b'  const [isBackendOnline, setIsBackendOnline] = useState(false);')
    lines.append(b'')
    lines.append(b'  useEffect(() => {')
    lines.append(b'    async function fetchData() {')
    lines.append(b'      try {')
    lines.append(b'        const res = await fetch("http://127.0.0.1:8000/api/v1/health", { headers: { "Content-Type": "application/json" } });')
    lines.append(b'        const h = await res.json();')
    lines.append(b'        setHealthData(h);')
    lines.append(b'        setIsBackendOnline(true);')
    lines.append(b'      } catch {')
    lines.append(b'        setIsBackendOnline(false);')
    lines.append(b'      }')
    lines.append(b'')
    lines.append(b'      // Load actual conversation and memory counts')
    lines.append(b'      try {')
    lines.append(b'        const token = localStorage.getItem("dash_access_token");')
    lines.append(b'        const headers: Record<string, string> = { "Content-Type": "application/json" };')
    lines.append(b'        if (token) headers["Authorization"] = `Bearer ${token}`;')
    lines.append(b'')
    lines.append(b'        const convRes = await fetch("http://127.0.0.1:8000/api/v1/conversations?limit=1&offset=0", { headers });')
    lines.append(b'        const convData = await convRes.json();')
    lines.append(b'        setConversationCount(convData.total || 0);')
    lines.append(b'')
    lines.append(b'        const memRes = await fetch("http://127.0.0.1:8000/api/v1/memory?limit=1&offset=0", { headers });')
    lines.append(b'        const memData = await memRes.json();')
    lines.append(b'        setMemoryCount(memData.total || 0);')
    lines.append(b'      } catch {')
    lines.append(b'        // Ignore errors for counts')
    lines.append(b'      }')
    lines.append(b'    }')
    lines.append(b'    fetchData();')
    lines.append(b'  }, []);')
    lines.append(b'')
    lines.append(b'  return (')
    lines.append(b'    <div>')
    lines.append(b'      <div className="page-header">')
    lines.append(b'        <div>')
    lines.append(b'          <h2 className="page-title">Dashboard</h2>')
    lines.append(b'          <p className="page-subtitle">Overview of your DASH assistant</p>')
    lines.append(CLOSE_DIV + b'        ')
    lines.append(CLOSE_DIV + b'      ')
    lines.append(CLOSE_DIV + b'')
    lines.append(b'')
    lines.append(b'      <div className="grid-4" style={{ marginBottom: 24 }}>')
    lines.append(b'        <div')
    lines.append(b'          className="glass-card animate-fade-in"')
    lines.append(b'          style={{ padding: 20, cursor: "pointer" }}')
    lines.append(b'          onClick={() => navigate("/chat")}')
    lines.append(b'        >')
    lines.append(b'          <div style={{ fontSize: 24, marginBottom: 12 }}>💬' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)", marginBottom: 4 }}>')
    lines.append(b'            {conversationCount}')
    lines.append(b'          ' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>Conversations' + CLOSE_DIV)
    lines.append(b'        ' + CLOSE_DIV)
    lines.append(b'')
    lines.append(b'        <div className="glass-card animate-fade-in" style={{ padding: 20 }}>')
    lines.append(b'          <div style={{ fontSize: 24, marginBottom: 12 }}>🧠' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)", marginBottom: 4 }}>')
    lines.append(b'            {memoryCount}')
    lines.append(b'          ' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>Memories' + CLOSE_DIV)
    lines.append(b'        ' + CLOSE_DIV)
    lines.append(b'')
    lines.append(b'        <div className="glass-card animate-fade-in" style={{ padding: 20 }}>')
    lines.append(b'          <div style={{ fontSize: 24, marginBottom: 12 }}>{isBackendOnline ? "\U0001f7e2" : "\U0001f534"}' + CLOSE_DIV)
    lines.append(b'          <div')
    lines.append(b'            style={{')
    lines.append(b'              fontSize: 28,')
    lines.append(b'              fontWeight: 700,')
    lines.append(b'              color: isBackendOnline ? "var(--success)" : "var(--danger)",')
    lines.append(b'              marginBottom: 4,')
    lines.append(b'            }}')
    lines.append(b'          >')
    lines.append(b'            {isBackendOnline ? "Online" : "Offline"}')
    lines.append(b'          ' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>Backend Status' + CLOSE_DIV)
    lines.append(b'        ' + CLOSE_DIV)
    lines.append(b'')
    lines.append(b'        <div className="glass-card animate-fade-in" style={{ padding: 20 }}>')
    lines.append(b'          <div style={{ fontSize: 24, marginBottom: 12 }}>📦' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 28, fontWeight: 700, color: "var(--text-primary)", marginBottom: 4 }}>')
    lines.append(b'            {healthData?.version || "---"}')
    lines.append(b'          ' + CLOSE_DIV)
    lines.append(b'          <div style={{ fontSize: 13, color: "var(--text-secondary)" }}>Version' + CLOSE_DIV)
    lines.append(b'        ' + CLOSE_DIV)
    lines.append(b'      ' + CLOSE_DIV)
    lines.append(b'')
    lines.append(b'      <div className="grid-2">')
    lines.append(b'        <div className="glass-card animate-fade-in" style={{ padding: 24 }}>')
    lines.append(b'          <h3 style={{ fontSize: 16, fontWeight: 600, marginBottom: 16, color: "var(--text-primary)" }}>')
    lines.append(b'            Quick Actions')
    lines.append(b'          ' + CLOSE_DIV.replace(b'/', b'').replace(b'div', b'/h3 missing...'))
    # This is getting too complex, let me just use a simpler approach
    
    return b'\n'.join(lines)

# Actually, let's just write the file using Python with proper escaping
path = r'c:\Users\Asus\Desktop\dash\apps\desktop\src\pages\Dashboard.tsx'

with open(path, 'rb') as f:
    data = f.read()

print(f"File size: {len(data)} bytes")
print(f"Contains </div>: {data.count(b'</div>')}")
print(f"Contains <div: {data.count(b'<div')}")
