"""Autonomous Agent System - Multi-agent coordination and execution."""

from __future__ import annotations

import asyncio
import logging
import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Callable, Dict, List, Optional

logger = logging.getLogger(__name__)


class AgentStatus(Enum):
    """Agent execution status."""
    IDLE = "idle"
    PLANNING = "planning"
    EXECUTING = "executing"
    WAITING = "waiting"
    COMPLETED = "completed"
    FAILED = "failed"


class AgentCapability(Enum):
    """Agent capabilities."""
    PLANNING = "planning"
    RESEARCH = "research"
    CODING = "coding"
    MEMORY = "memory"
    DESKTOP = "desktop"
    BROWSER = "browser"
    MONITORING = "monitoring"
    REMINDER = "reminder"
    TASK_EXECUTION = "task_execution"


@dataclass
class AgentTask:
    """A task for an agent to execute."""
    id: str
    description: str
    agent_type: str
    priority: int = 5
    context: Dict[str, Any] = field(default_factory=dict)
    dependencies: List[str] = field(default_factory=list)
    status: AgentStatus = AgentStatus.IDLE
    result: Optional[Any] = None
    error: Optional[str] = None
    created_at: float = 0.0
    started_at: float = 0.0
    completed_at: float = 0.0
    
    def __post_init__(self):
        if not self.created_at:
            self.created_at = datetime.now().timestamp()
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "description": self.description,
            "agent_type": self.agent_type,
            "priority": self.priority,
            "context": self.context,
            "dependencies": self.dependencies,
            "status": self.status.value,
            "result": self.result,
            "error": self.error,
            "created_at": self.created_at,
            "started_at": self.started_at,
            "completed_at": self.completed_at,
        }


@dataclass
class AgentPlan:
    """A plan generated by the planner agent."""
    id: str
    goal: str
    steps: List[AgentTask]
    estimated_duration: float = 0.0
    confidence: float = 0.0
    
    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "goal": self.goal,
            "steps": [step.to_dict() for step in self.steps],
            "estimated_duration": self.estimated_duration,
            "confidence": self.confidence,
        }


class BaseAgent(ABC):
    """Base class for all autonomous agents."""
    
    def __init__(self, name: str, capabilities: List[AgentCapability]):
        self.name = name
        self.capabilities = capabilities
        self.status = AgentStatus.IDLE
        self.current_task: Optional[AgentTask] = None
        
    @abstractmethod
    async def execute(self, task: AgentTask) -> Any:
        """Execute a task.
        
        Args:
            task: Task to execute
            
        Returns:
            Task result
        """
        pass
    
    @abstractmethod
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan how to achieve a goal.
        
        Args:
            goal: Goal to achieve
            context: Execution context
            
        Returns:
            Execution plan
        """
        pass
    
    def can_handle(self, task: AgentTask) -> bool:
        """Check if this agent can handle a task."""
        return task.agent_type == self.name.lower()


class PlannerAgent(BaseAgent):
    """Agent that plans complex tasks."""
    
    def __init__(self):
        super().__init__("planner", [AgentCapability.PLANNING])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a planning task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            plan = await self.plan(task.description, task.context)
            self.status = AgentStatus.COMPLETED
            return plan
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Generate a plan for achieving a goal."""
        # Simple planning - break goal into steps
        plan_id = str(uuid.uuid4())
        
        # Analyze goal to determine required agent types
        agent_types = self._determine_required_agents(goal)
        
        # Create tasks for each agent type
        steps = []
        for i, agent_type in enumerate(agent_types):
            step = AgentTask(
                id=str(uuid.uuid4()),
                description=f"Execute {agent_type} step for: {goal}",
                agent_type=agent_type,
                priority=max(1, 10 - i),
                context=context,
            )
            if i > 0:
                step.dependencies = [steps[i-1].id]
            steps.append(step)
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=steps,
            estimated_duration=len(steps) * 300,  # 5 min per step
            confidence=0.8,
        )
    
    def _determine_required_agents(self, goal: str) -> List[str]:
        """Determine which agents are needed for a goal."""
        goal_lower = goal.lower()
        
        agents = []
        
        if any(word in goal_lower for word in ["research", "find", "search", "look up"]):
            agents.append("research")
        
        if any(word in goal_lower for word in ["code", "program", "develop", "implement", "fix"]):
            agents.append("coding")
        
        if any(word in goal_lower for word in ["remember", "memory", "store", "recall"]):
            agents.append("memory")
        
        if any(word in goal_lower for word in ["desktop", "window", "application", "file"]):
            agents.append("desktop")
        
        if any(word in goal_lower for word in ["browser", "web", "website", "page"]):
            agents.append("browser")
        
        if not agents:
            agents.append("general")
        
        return agents


class ResearchAgent(BaseAgent):
    """Agent that performs research tasks."""
    
    def __init__(self):
        super().__init__("research", [AgentCapability.RESEARCH])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a research task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            # Perform web search
            from dash_backend.tools.tool_manager import get_tool_manager
            manager = get_tool_manager()
            
            result = await manager.execute("search_web", {"query": task.description})
            
            self.status = AgentStatus.COMPLETED
            return result
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan a research task."""
        plan_id = str(uuid.uuid4())
        
        step = AgentTask(
            id=str(uuid.uuid4()),
            description=f"Research: {goal}",
            agent_type="research",
            context=context,
        )
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=[step],
            estimated_duration=300,
            confidence=0.9,
        )


class CodingAgent(BaseAgent):
    """Agent that performs coding tasks."""
    
    def __init__(self):
        super().__init__("coding", [AgentCapability.CODING])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a coding task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            # Use AI to generate code
            from dash_backend.services.ai_router.router import get_ai_router
            router = get_ai_router()
            
            messages = [
                {"role": "system", "content": "You are a coding assistant. Provide code snippets and explanations."},
                {"role": "user", "content": task.description},
            ]
            
            result = await router.route(
                query=task.description,
                messages=messages,
                force_model="qwen2.5-coder:7b",
            )
            
            self.status = AgentStatus.COMPLETED
            return result
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan a coding task."""
        plan_id = str(uuid.uuid4())
        
        step = AgentTask(
            id=str(uuid.uuid4()),
            description=f"Code: {goal}",
            agent_type="coding",
            context=context,
        )
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=[step],
            estimated_duration=600,
            confidence=0.85,
        )


class MemoryAgent(BaseAgent):
    """Agent that manages memory operations."""
    
    def __init__(self):
        super().__init__("memory", [AgentCapability.MEMORY])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a memory task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            from dash_backend.memory.service import search_memories, save_memory
            from dash_backend.db.session import AsyncSessionLocal
            
            async with AsyncSessionLocal() as session:
                if "search" in task.description.lower():
                    results = await search_memories(session, task.context.get("user_id", ""), task.description)
                    self.status = AgentStatus.COMPLETED
                    return {"results": [m.to_dict() for m in results]}
                else:
                    memory = await save_memory(
                        session,
                        task.context.get("user_id", ""),
                        task.description,
                        category=task.context.get("category"),
                    )
                    self.status = AgentStatus.COMPLETED
                    return memory.to_dict()
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan a memory task."""
        plan_id = str(uuid.uuid4())
        
        step = AgentTask(
            id=str(uuid.uuid4()),
            description=f"Memory: {goal}",
            agent_type="memory",
            context=context,
        )
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=[step],
            estimated_duration=60,
            confidence=0.95,
        )


class DesktopAgent(BaseAgent):
    """Agent that controls desktop operations."""
    
    def __init__(self):
        super().__init__("desktop", [AgentCapability.DESKTOP])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a desktop task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            from dash_backend.tools.tool_manager import get_tool_manager
            manager = get_tool_manager()
            
            # Map task description to tool
            if "open" in task.description.lower():
                result = await manager.execute("open_application", {"path": task.context.get("path", "")})
            elif "close" in task.description.lower():
                result = await manager.execute("close_application", {"name": task.context.get("name", "")})
            else:
                result = await manager.execute("list_running_processes", {})
            
            self.status = AgentStatus.COMPLETED
            return result
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan a desktop task."""
        plan_id = str(uuid.uuid4())
        
        step = AgentTask(
            id=str(uuid.uuid4()),
            description=f"Desktop: {goal}",
            agent_type="desktop",
            context=context,
        )
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=[step],
            estimated_duration=120,
            confidence=0.9,
        )


class BrowserAgent(BaseAgent):
    """Agent that controls browser operations."""
    
    def __init__(self):
        super().__init__("browser", [AgentCapability.BROWSER])
        
    async def execute(self, task: AgentTask) -> Any:
        """Execute a browser task."""
        self.status = AgentStatus.EXECUTING
        self.current_task = task
        
        try:
            from dash_backend.tools.tool_manager import get_tool_manager
            manager = get_tool_manager()
            
            if "search" in task.description.lower():
                result = await manager.execute("search_web", {"query": task.context.get("query", "")})
            else:
                result = await manager.execute("open_url", {"url": task.context.get("url", "")})
            
            self.status = AgentStatus.COMPLETED
            return result
        except Exception as e:
            self.status = AgentStatus.FAILED
            task.error = str(e)
            raise
    
    async def plan(self, goal: str, context: Dict[str, Any]) -> AgentPlan:
        """Plan a browser task."""
        plan_id = str(uuid.uuid4())
        
        step = AgentTask(
            id=str(uuid.uuid4()),
            description=f"Browser: {goal}",
            agent_type="browser",
            context=context,
        )
        
        return AgentPlan(
            id=plan_id,
            goal=goal,
            steps=[step],
            estimated_duration=180,
            confidence=0.9,
        )


class AgentCoordinator:
    """Coordinates multiple agents for complex tasks."""
    
    def __init__(self):
        self._agents: Dict[str, BaseAgent] = {}
        self._task_queue: List[AgentTask] = []
        self._running = False
        self._execution_task: Optional[asyncio.Task] = None
        
        # Register built-in agents
        self._register_builtin_agents()
    
    def _register_builtin_agents(self) -> None:
        """Register built-in agents."""
        self._agents["planner"] = PlannerAgent()
        self._agents["research"] = ResearchAgent()
        self._agents["coding"] = CodingAgent()
        self._agents["memory"] = MemoryAgent()
        self._agents["desktop"] = DesktopAgent()
        self._agents["browser"] = BrowserAgent()
    
    def register_agent(self, agent: BaseAgent) -> None:
        """Register a custom agent."""
        self._agents[agent.name.lower()] = agent
        logger.info("Registered agent: %s", agent.name)
    
    async def execute_goal(self, goal: str, context: Dict[str, Any]) -> Dict[str, Any]:
        """Execute a goal using agent coordination.
        
        Args:
            goal: Goal to achieve
            context: Execution context
            
        Returns:
            Execution results
        """
        # First, use planner to create a plan
        planner = self._agents["planner"]
        plan = await planner.plan(goal, context)
        
        results = {
            "goal": goal,
            "plan": plan.to_dict(),
            "executions": [],
        }
        
        # Execute plan steps
        for step in plan.steps:
            try:
                # Wait for dependencies
                for dep_id in step.dependencies:
                    # In production, wait for dependency completion
                    pass
                
                # Find appropriate agent
                agent = self._agents.get(step.agent_type)
                if not agent:
                    # Use planner as fallback
                    agent = self._agents["planner"]
                
                # Execute step
                step.status = AgentStatus.EXECUTING
                step.started_at = datetime.now().timestamp()
                
                result = await agent.execute(step)
                
                step.status = AgentStatus.COMPLETED
                step.completed_at = datetime.now().timestamp()
                step.result = result
                
                results["executions"].append({
                    "step_id": step.id,
                    "agent": agent.name,
                    "status": "completed",
                    "result": result,
                })
                
            except Exception as e:
                step.status = AgentStatus.FAILED
                step.error = str(e)
                step.completed_at = datetime.now().timestamp()
                
                results["executions"].append({
                    "step_id": step.id,
                    "agent": agent.name if agent else "unknown",
                    "status": "failed",
                    "error": str(e),
                })
                
                logger.error("Step execution failed: %s", e)
        
        return results
    
    def get_agent(self, name: str) -> Optional[BaseAgent]:
        """Get an agent by name."""
        return self._agents.get(name.lower())
    
    def list_agents(self) -> List[BaseAgent]:
        """List all registered agents."""
        return list(self._agents.values())


_agent_coordinator: Optional[AgentCoordinator] = None


def get_agent_coordinator() -> AgentCoordinator:
    global _agent_coordinator
    if _agent_coordinator is None:
        _agent_coordinator = AgentCoordinator()
    return _agent_coordinator
