"""Terms and Conditions for DASH.

Version 1.0 — Effective: September 7, 2026
"""

TERMS_VERSION = "1.0"
TERMS_EFFECTIVE = "2026-09-07"

TERMS_AND_CONDITIONS = r"""# DASH Terms and Conditions

**Version:** 1.0
**Effective Date:** September 7, 2026
**Last Updated:** September 7, 2026

---

## 1. Acceptance of Terms

By installing, accessing, or using DASH (the "Software"), you agree
to be bound by these Terms and Conditions. If you do not agree, do
not use the Software.

---

## 2. Description of Service

DASH is a personal AI operating system that runs on your local
machine. It provides:

- AI-powered chat and voice interaction
- Long-term memory and context management
- Goal tracking and task management
- System monitoring and predictive analysis
- Desktop control and automation
- Privacy-first design with local data storage

---

## 3. Account Responsibilities

You are responsible for:

- Maintaining the security of your account credentials
- All activity that occurs under your account
- Keeping your contact information current
- Notifying us of any unauthorized use of your account

---

## 4. Acceptable Use

You may use DASH for lawful purposes only. You agree not to:

- Use DASH to violate any applicable law or regulation
- Attempt to gain unauthorized access to any part of the Software
- Interfere with or disrupt the Software or its infrastructure
- Use DASH to transmit harmful, abusive, or illegal content
- Reverse engineer, decompile, or disassemble the Software
- Remove or alter any proprietary notices or labels

---

## 5. Prohibited Misuse

The following uses are specifically prohibited:

- Using DASH to perform unauthorized actions on your system
- Attempting to extract or exfiltrate data from the Software
- Circumventing authentication or authorization controls
- Using automated means to access the Software without permission
- Reselling or redistributing the Software without authorization

---

## 6. AI Limitations

DASH uses artificial intelligence models that have inherent limitations:

- **Not omniscient:** DASH may produce incorrect, incomplete, or
  outdated information
- **Not a substitute for professional advice:** DASH does not provide
  legal, medical, financial, or other professional advice
- **Probabilistic output:** AI-generated responses are based on
  statistical patterns and may vary between sessions
- **Context limitations:** DASH's understanding is limited to the
  information available to it
- **No guarantee of accuracy:** While DASH strives for accuracy, it
  makes no guarantees about the correctness of its output

You are solely responsible for verifying any information provided by
DASH before relying on it for important decisions.

---

## 7. Third-Party Integrations

DASH may integrate with third-party AI providers (Ollama, OpenAI,
Anthropic, Google Gemini, Groq) when you choose to configure them:

- Third-party services are governed by their own terms of service
- DASH is not responsible for the actions of third-party providers
- You are responsible for any costs incurred through third-party
  API usage
- Third-party data processing is described in the Privacy Policy

---

## 8. Service Availability

- DASH runs entirely on your local machine
- Local features (chat, memory, monitoring) are available offline
- Cloud AI features require an active internet connection and a
  configured provider
- We do not guarantee uninterrupted availability of cloud AI
  providers

---

## 9. Intellectual Property

### 9.1 DASH Ownership

DASH and its original content, features, and functionality are owned
by the DASH project and are protected by copyright, trademark, and
other intellectual property laws.

### 9.2 Your Content

You retain all rights to content you create, input, or generate
through DASH. DASH does not claim ownership of your data, conversations,
memories, or other user-generated content.

### 9.3 AI-Generated Content

Content generated by AI models through DASH is provided to you for
use as you see fit. Ownership of AI-generated content may depend on
the terms of the AI provider used.

---

## 10. User Content

You are solely responsible for content you input into DASH. By using
DASH, you represent that:

- You have the right to input any content you provide
- Your content does not infringe on third-party rights
- Your content does not violate any applicable law

---

## 11. Limitation of Liability

To the maximum extent permitted by law:

- DASH is provided "as is" and "as available" without warranties
  of any kind
- We disclaim all warranties, express or implied, including
  merchantability, fitness for a particular purpose, and
  non-infringement
- We are not liable for any indirect, incidental, special,
  consequential, or punitive damages
- Our total liability shall not exceed the amount you paid for
  the Software (if any)
- We are not liable for damages arising from AI-generated output,
  system failures, data loss, or third-party actions

---

## 12. Indemnification

You agree to indemnify and hold harmless the DASH project and its
contributors from any claims, losses, or damages arising from:

- Your use of the Software
- Your violation of these Terms
- Your violation of any rights of a third party
- Content you input into the Software

---

## 13. Modifications to Terms

We reserve the right to modify these Terms at any time. Changes will
be effective when posted. Your continued use of DASH after changes
constitutes acceptance of the modified Terms.

---

## 14. Termination

You may terminate your use of DASH at any time by:

- Uninstalling the Software
- Deleting your account and data through the Privacy API

We may terminate or suspend your access if you violate these Terms.

---

## 15. Governing Law

These Terms shall be governed by the laws of India, without regard
to conflict of law provisions. Any disputes shall be resolved in the
courts of India.

---

## 16. Severability

If any provision of these Terms is found to be unenforceable, the
remaining provisions shall continue in full force and effect.

---

## 17. Entire Agreement

These Terms, together with the Privacy Policy, constitute the entire
agreement between you and DASH regarding the use of the Software.

---

## 18. Contact

For questions about these Terms:

- **Email:** support@dash-ai.dev
- **GitHub Issues:** https://github.com/shadow909559/dash/issues
"""

__all__ = ["TERMS_AND_CONDITIONS", "TERMS_VERSION", "TERMS_EFFECTIVE"]
